# Generated by Django 4.2.4 on 2023-11-09 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutzenapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offer_type',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Offer_Type',
        ),
    ]
